# Generated by Django 4.1.2 on 2022-11-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phsyical_number", models.IntegerField()),
                ("reserved_number", models.IntegerField()),
                ("active_number", models.IntegerField()),
                ("product_insertion_time", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                    ),
                ),
            ],
        ),
    ]
