# Generated by Django 4.1.2 on 2022-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="active_number",
            field=models.IntegerField(default=0),
        ),
    ]
