# Generated by Django 4.1.2 on 2022-11-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("M", "Mexanik"), ("A", "Avto"), ("H", "Hecne")],
                        default="Hecne",
                        max_length=1,
                    ),
                ),
                ("contract_code", models.CharField(max_length=80)),
                ("contract", models.CharField(blank=True, max_length=100)),
                ("reserved_status", models.BooleanField()),
                ("sale_status", models.BooleanField()),
                ("reserved_date", models.DateField()),
                ("sale_number", models.IntegerField()),
                ("sold_time", models.DateTimeField(auto_now_add=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stock.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_sale_number", models.IntegerField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Sale.sale",
                    ),
                ),
            ],
        ),
    ]
