# Generated by Django 4.1.2 on 2022-11-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sale", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="sale_status",
        ),
    ]
