# Generated by Django 4.1.2 on 2022-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sale", "0004_alter_sale_prev_sale_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="prev_sale_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
